language: minimal

script:
  - make _gen-modules

after_success:
  - git config user.email "travis@travis-ci.com"
  - git config user.name "Travis"
  - git add .
  - git commit -m "updated README.md"
  - git push https://${GITHUB_API_KEY}@${GH_REF} HEAD:master

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/Shkurupii/training-aws-modules
