language: minimal

script:
- make _gen-modules

after_success:
  - git config user.email "travis@travis-ci.com"
  - git config user.name "Travis"
  - git add .  */README.md
  - git commit -m "updated README.md"
  - git push https://Shkurupii:${GITHUB_API_KEY}@${GH_REF} HEAD:master

branches:
  only:
    - master
